version: '3.8'

services:
  mysql-db:
    image: mysql:5.7
    env_file: vars.env
    ports:
      - "3307:3306"
    restart: always

  app:
    build: .
    ports:
      - "9091:9090"
    env_file: vars.env
    depends_on:
      - mysql-db
    restart: always
    volumes:
      - .:/core